.gitignore, contracts/CardPaymentProcessorUpgradeable.sol, contracts/base/PausableExUpgradeable.sol, contracts/mocks/ERC20UpgradeableMock.sol, contracts/mocks/base/PausableExUpgradeableMock.sol, hardhat.config.ts, package-lock.json, package.json, test-utils/README.md, test-utils/eth.ts, test-utils/misc.ts, test/CardPaymentProcessorUpgradeable.test.ts, test/base/PausableExUpgradeable.test.ts
1.  The card payment processor contract has been rewritten to Solidity 0.8.x based on the code from 
[brlc-token](https://github.com/cloudwalk/brlc-token) repo. Version 0.8.15 was used for compilation and testing.
2.  Instead of using the whitelist and pauser the roles have been introduced based on the [OpenZeppelin access control contracts](https://docs.openzeppelin.com/contracts/4.x/access-control). There are three roles now: the owner, the pauser, the executor.
3. The tests have been renovated too.
The updated and newly developed tests have been successfully run on the following blockchains:
1. Internal Hardhat net.
2. Substrate with Frontier layer built from the [cloudwalk-network](https://github.com/cloudwalk/cloudwalk-network) repo, branch …
=> Card payment processor implementation

.gitignore, contracts/CardPaymentProcessorUpgradeable.sol, contracts/base/PausableExUpgradeable.sol, contracts/mocks/ERC20UpgradeableMock.sol, contracts/mocks/base/PausableExUpgradeableMock.sol, hardhat.config.ts, package-lock.json, package.json, test-utils/README.md, test-utils/eth.ts, test-utils/misc.ts, test/CardPaymentProcessorUpgradeable.test.ts, test/base/PausableExUpgradeable.test.ts
1. All revert messages in the card payment processor contract have been replaced with custom errors.
1. This PR should be merged after [PR#1](https://github.com/cloudwalk/brlc-periphery/pull/1).
The updated and newly developed tests have been successfully run on the following blockchains:
1. Internal Hardhat net.
2. Substrate with Frontier layer built from the [cloudwalk-network](https://github.com/cloudwalk/cloudwalk-network) repo, branch [main](https://github.com/cloudwalk/cloudwalk-network), commit [350445547016ce83c5ce781ac8871194439b0e4f](https://github.com/cloudwalk/cloudwalk-network/commit/350445547016ce83c5ce781ac8871194439b0e4f).
_NOTE 1_: When running a local node of Substrate with Frontier layer for testing use the node in the archive mode like in the following command:
```bash …
```
=> Using custom errors in the card payment processor contract

contracts/CardPaymentProcessor.sol, contracts/CardPaymentProcessorStorage.sol, contracts/base/BlacklistControlUpgradeable.sol, contracts/base/PauseControlUpgradeable.sol, contracts/base/RescueControlUpgradeable.sol, contracts/base/StoragePlaceholder.sol, contracts/mocks/base/BlacklistControlUpgradeableMock.sol, contracts/mocks/base/RescueControlUpgradeableMock.sol, contracts/mocks/tokens/ERC20UpgradeableMock.sol, test/CardPaymentProcessor.test.ts, test/base/BlacklistControlUpgradeable.test.ts, test/base/PauseControlUpgradeable.test.ts, test/base/RescueControlUpgradeable.test.ts
1. The contract has been renamed: `CardPaymentProcessorUpgradeable` => `CardPaymentProcessor`.
2. The `ERC20UpgradeableMock` contract has been moved to the `mocks/tokens` directory.
3. The following base contracts with the appropriate roles have been introduced:
* BlacklistControlUpgradeable -- `BLACKLISTER_ROLE`;
* RescueControlUpgradeable -- `RESCUER_ROLE`;
* StoragePlaceholder -- no additional role.
4. The CPP contract has been inherited from the new base contracts above.
5. Some improvements in the contract code, its comments and its tests.
The updated and newly developed tests have been successfully run on the following blockchains:
1. Internal Hardhat net.
2. Substrate with Frontier layer built from the [cloudwalk-network](https://github.com/cloudwalk/cloudwalk-network) repo, commit …
=> Card payment processor contract improvements

contracts/CardPaymentProcessor.sol, contracts/CardPaymentProcessorStorage.sol, contracts/PixCashier.sol, contracts/PixCashierStorage.sol, contracts/base/BlacklistControlUpgradeable.sol, contracts/base/PauseControlUpgradeable.sol, contracts/base/RescueControlUpgradeable.sol, contracts/base/StoragePlaceholder.sol, contracts/interfaces/IERC20Mintable.sol, contracts/interfaces/IPixCashier.sol, contracts/mocks/base/BlacklistControlUpgradeableMock.sol, contracts/mocks/base/RescueControlUpgradeableMock.sol, contracts/mocks/tokens/ERC20UpgradeableMock.sol, test/CardPaymentProcessor.test.ts, test/PixCashier.test.ts, test/base/BlacklistControlUpgradeable.test.ts, test/base/PauseControlUpgradeable.test.ts, test/base/RescueControlUpgradeable.test.ts
1.  The PIX cashier contract has been rewritten to Solidity 0.8.x based on the code from 
[brlc-token](https://github.com/cloudwalk/brlc-token) repo. Version 0.8.15 was used for compilation and testing.
2.  Instead of using the whitelist and pauser the appropriate roles have been introduced based on the [OpenZeppelin access control contracts](https://docs.openzeppelin.com/contracts/4.x/access-control).
3. The caller blacklist checking has been add for the `cashOut()` function.
4. Inheritance from the `StoragePlaceholder200` contract has been used to reserve 200 storage slots for the future possible improvements of the contract.
5. The following roles are currently used in the contract:
* `OWNER_ROLE` -- an account with this role owns the contract and can grant and remove other roles …
=> Pix cashier contract

contracts/CardPaymentProcessor.sol, contracts/CardPaymentProcessorStorage.sol, contracts/PixCashier.sol, contracts/PixCashierStorage.sol, contracts/TokenDistributor.sol, contracts/base/BlacklistControlUpgradeable.sol, contracts/base/PauseControlUpgradeable.sol, contracts/base/RescueControlUpgradeable.sol, contracts/base/StoragePlaceholder.sol, contracts/interfaces/IERC20Mintable.sol, contracts/interfaces/IPixCashier.sol, contracts/interfaces/ITokenDistributor.sol, contracts/mocks/base/BlacklistControlUpgradeableMock.sol, contracts/mocks/base/RescueControlUpgradeableMock.sol, contracts/mocks/tokens/ERC20UpgradeableMock.sol, test/CardPaymentProcessor.test.ts, test/PixCashier.test.ts, test/TokenDistributor.test.ts, test/base/BlacklistControlUpgradeable.test.ts, test/base/PauseControlUpgradeable.test.ts, test/base/RescueControlUpgradeable.test.ts
1.  The Multisend contract has been rewritten to Solidity 0.8.x based on the code from 
[brlc-token](https://github.com/cloudwalk/brlc-token) repo. Version 0.8.15 was used for compilation and testing.
2. The contract has been renamed to `TokenDistributor`.
3.  Instead of using the whitelist and pauser the appropriate roles have been introduced based on the [OpenZeppelin access control contracts](https://docs.openzeppelin.com/contracts/4.x/access-control).
4. Inheritance from the `StoragePlaceholder200` contract has been used to reserve 200 storage slots for the future possible improvements of the contract.
5. The following roles are currently used in the contract:
* `OWNER_ROLE` -- an account with this role owns the contract and can grant and remove other roles to/from accounts. 
* …
=> Token distributor contract

contracts/CardPaymentProcessor.sol, contracts/CardPaymentProcessorStorage.sol, contracts/CashbackDistributor.sol, contracts/CashbackDistributorStorage.sol, contracts/interfaces/ICardPaymentCashback.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/interfaces/ICashbackDistributor.sol, contracts/mocks/CashbackDistributorMock.sol, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts
1. The refund logic has been added to the `CardPaymentProcessor`. The `refundPayment()` function can be used to execute a refund related to a payment, e.g. due to of a voucher, charge back, etc.  
2. The `cashOutAccount` address has been moved from the parameter of functions to the `_cashOutAccount` storage variable of the `CardPaymentProcessor` contract. It is needed to supply refunds after confirming a payment.
3. The new `CashbackDistributor` contract has been introduced. It is used for distribute cashback.
4. The cashback logic has been added to the `CardPaymentProccessor`. The rate of the cashback is defined by the `_cashbackRateInPermil` storage variable. Cashback giving is organized through the new `CashbackDistributor` contract.
5. The tests have been updated according to the …
=> Refund and cashback

contracts/CardPaymentProcessor.sol, contracts/CardPaymentProcessorStorage.sol, contracts/CashbackDistributor.sol, contracts/CashbackDistributorStorage.sol, contracts/PixCashier.sol, contracts/PixCashierStorage.sol, contracts/interfaces/ICardPaymentCashback.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/interfaces/ICashbackDistributor.sol, contracts/interfaces/IPixCashier.sol, contracts/mocks/CashbackDistributorMock.sol, contracts/mocks/tokens/ERC20UpgradeableMock.sol, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts, test/PixCashier.test.ts
1. The logic of the `PixCashier` contract has been redefined with intensive usage of the off-chain transaction identifier (`txId`).
2. Functions related to cash-out operations have been renamed.
3. The new `requestCashOutFrom()` function has been introduced to allow accounts with the `CASHIER_ROLE` role request a cash-out of other accounts.
4. Now all the cash-out operations except requesting can be done only through the appropriate `txId`.
5. Now all the cash-out operations except requesting can be executed only by accounts with the `CASHIER_ROLE` role.
6. The tests have been updated according to the changes in contracts.
The tests have been successfully run on the internal Hardhat net.
Coverage:
=> PIX Cashier V2

contracts/PixCashier.sol, contracts/interfaces/IPixCashier.sol, test/PixCashier.test.ts
1. The `requestCashOut()` function has been removed from the `PixCashier` contract. Because of that only accounts with the `CASHIER_ROLE` role can now request cash-out operations for some account (through the `requestCashOutFrom()` function). Previously any account could do the request through the removed function.
2. The blacklist checking option has been added to the `requestCashOutFrom()`. If an account for which a cash-out is requested is in the blacklist the `requestCashOutFrom()`  function will be reverted.
3. The tests have been updated accordingly. 
All contracts are 100% covered with tests:
=> PIX Cashier. Remove the direct user call of the contract

contracts/CardPaymentProcessor.sol, contracts/CashbackDistributor.sol, contracts/interfaces/ICardPaymentCashback.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/interfaces/ICashbackDistributor.sol, contracts/mocks/CashbackDistributorMock.sol, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts
1. CPP stands for the `CardPaymentProcessor` contract.
2. CD stands for the `CashbackDistributor` contract.
1.  The new function of CPP to update the amount of a payment: `function updatePaymentAmount(uint256 newAmount, bytes16 authorizationId)`.
2.  The parameter `newAmount` must not exceed the cumulative refund amount of the payment.
3.  The function can be called only by an account with the `EXECUTOR_ROLE` role.
4.  The payment must be uncleared.
5.  During execution the function can increase or decrease the amount of the payment and the related cashback.
6.  To decrease cashback the existen `revokeCashback()` function of CD is called.
7.  To increase cashback the newly added `increaseCashback()` function of CD is called.
8.  If the `updatePaymentAmount()` function of CPP executes …
=> CPP. Introduce a function to update the amount of a payment

contracts/CardPaymentProcessor.sol, contracts/CashbackDistributor.sol, contracts/interfaces/ICardPaymentCashback.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/interfaces/ICashbackDistributor.sol, contracts/mocks/CashbackDistributorMock.sol, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts
1. CPP stands for the CardPaymentProcessor contract.
2. CD stands for the CashbackDistributor contract.
1.  The `correlationId` parameter has been added to the following functions and events of CPP:
* function `updatePaymentAmount()`;
* function `refundPayment()`;
* event `UpdatePaymentAmount`;
* event `RefundPayment`.
2. The new parameter is not used inside the functions and is sent directly to the events. It is needed for the backend app.
3. Tests have been updated accordingly.
=> Add the "correlationId" parameter to some functions and events of CPP

contracts/PixCashier.sol, contracts/interfaces/IPixCashier.sol, test/PixCashier.test.ts
Code changes:
1. Two new functions were added: `cashInBatch` and `requestCashOutBatch`. These function allow cashier to perform multiple cash-in operations or requests by calling only one function.
2. Old functions used to perform multiple actions were renamed similarly to new functions.
3. Tests were reorganized, so the positive cases are tested before the negative.
4. NatSpec references were added to all internal functions.
All new functionality was covered with tests and successfully tested:
=> Add new batch functions and reformat tests

contracts/CardPaymentProcessor.sol, contracts/interfaces/ICardPaymentProcessor.sol, test-utils/checkers.ts, test/CardPaymentProcessor.test.ts
1. CPP stands for the CardPaymentProcessor contract.
2. CD stands for the CashbackDistributor contract.
1. The ability to specify an extra payment amount in CPP has been provided.
2. The extra payment amount is excluded from the cashback calculation.
3. The payment amount that is used in the cashback calculation is now called the "base amount".
4. The following relations are assumed for a CPP payment:
* `sumAmount = baseAmount + extraAmount`;
* `totalAmount = sumAmount - refundAmount = baseAmount + extraAmount - refundAmount`.
5. The logic of interactions CPP with CD have also been updated accordingly.
1. A new field in the `Payment` structure has been added: `Payment.extraAmount`.
2. An existing field of the `Payment` structure has been renamed : `Payment.amount` => `Payment.baseAmount`. …
=> Add the extra payment amount feature to CPP

contracts/CashbackDistributor.sol, contracts/interfaces/ICashbackDistributor.sol, test/CashbackDistributor.test.ts
1. Event `IncreaseCashback` of the `CashbackDistributor` smart-contract. A new field `totalAmount` has been added. It corresponds to the result amount of cashback that the recipient has after the increase operation. The new event definition:
```solidity
event IncreaseCashback(
address token,
CashbackKind cashbackKind,
CashbackStatus cashbackStatus,
IncreaseStatus indexed status,
bytes32 indexed externalId,
address indexed recipient,
uint256 amount,
uint256 totalAmount,
address sender,
uint256 nonce
);
```
2. Event `RevokeCashback` of the `CashbackDistributor` smart-contract.  A new field `totalAmount` has been added. It corresponds to the result amount of cashback that the recipient has after the revocation operation. The new event definition:
```solidity
event RevokeCashback(
address …
```
=> Extend the CashbackDistributor contract events with a new field of cashback total amount

contracts/CardPaymentProcessor.sol, contracts/CashbackDistributor.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/interfaces/ICashbackDistributor.sol, test-utils/checkers.ts, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts
1. CPP stands for the `CardPaymentProcessor` smart-contract.
2. CD stands for the `CashbackDistributor` smart-contract.
1. A new function to support subsidized payments and special cashback rate has been added:
```solidity
/**
* @dev Makes a card payment for a given account initiated by a service account.
*
* The payment can be subsidized with full or partial reimbursement from a specified sponsor account.
* The payment cashback rate can be taken from the contract settings or specified at the call.
* If cashback is disabled in the contract it will not be sent in any case.
*
* Transfers the underlying tokens from the account and/or sponsor to this contract.
* This function can be called by a limited number of accounts that are allowed to execute processing operations.
*
* Emits a …
```
=> Introduce subsidized payments and cashback control to the CardPaymentProcessor contract

contracts/CardPaymentProcessor.sol, contracts/CashbackDistributor.sol, contracts/PixCashier.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/interfaces/ICashbackDistributor.sol, test-utils/checkers.ts, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts, test/PixCashier.test.ts
There was a possibility to widely reuse the same `txId` value for a new PIX cash-out requests in the `PixCashier` smart-contract.
Now reuse `txId` is allowed only if the previous cash-out operation has the `Reversed` status and the account addresses of the previous and new operation are the same.
If an operation with the provided `txId` does not exist no restrictions are applied for the new cash-out requests.
The full list of restrictions for cash-out request transactions related to `txId`:
1. `TxId` of a confirmed cash-out operation cannot be used again.
2. `TxId` of a pending cash-out operation cannot be used again.
3. `TxId` of a reversed cash-out operation cannot be used again for a different account.
1. New logic for checking cash-out request has been introduced:
```solidity
if …
```
=> Prevent txId reusing in the PixCashier contract

contracts/CardPaymentProcessor.sol, test/CardPaymentProcessor.test.ts
The improvements eliminate a handling bug when the initial cashback is capped.
The following rules have been applied to cashback changes:
1. If the base amount of a payment decreases (in the `updatePaymentAmount()` function) or a payment is refunding the new cashback amount cannot be higher than the old cashback amount if the old cashback was capped.
2. If the base amount of a payment increases (in the `updatePaymentAmount()` function) the new cashback amount can be higher than the old cashback amount even if the old cashback amount was capped.
3. Calling functions of the `CashbackDistributor` contract when the cashback amount change is zero. If the new base amount of a payment is greater than the old one the `increaseCashback()` function of the `CashbackDistributor` contract will be …
=> Improve cashback changes handling in CardPaymentProcessor contract

contracts/CardPaymentProcessor.sol, contracts/interfaces/ICardPaymentProcessor.sol, test/CardPaymentProcessor.test.ts
1. Two new functions have been added to the CardPaymentProcessor contract (CPP): `clearAndConfirmPayment(bytes16 authorizationId)` and `clearAndConfirmPayments(bytes16[] memory authorizationIds)`
2. Function `clearAndConfirmPayment()` executes consequently clearing and confirm operations for a single payment by its authorization ID.
3. Function `clearAndConfirmPayments()` does the same as the function above but for several payments by their authorization IDs.
| Folder or File                              | % Stmts | % Branch | % Funcs | % Lines |
|:--------------------------------------------|--------:|---------:|--------:|--------:|
| contracts/                                  |     100 |    98.33 |     100 |     100 |
| &nbsp;&nbsp;CardPaymentProcessor.sol        |     100 |     99.3 | …
=> Unite clearing and confirmation operations for a payment in the CardPaymentProcessor contract

contracts/PixCashier.sol, contracts/PixCashierStorage.sol, contracts/interfaces/IPixCashier.sol, test/PixCashier.test.ts
1. Each time a cash-in operation with a given off-chain transaction identifier `txId` is executed the information about it stored on the `PixCashier` contract using the following code entities:
```solidity
enum CashInStatus {
Nonexistent, // 0
Executed     // 1
}
struct CashInOperation {
CashInStatus status;  // The status of the cash-in operation according to the {CashInStatus} enum.
address account;      // The owner of tokens to cash-in.
uint256 amount;       // The amount of tokens to cash-in.
}
// The mapping of a cash-out operation structure for a given off-chain transaction identifier (`txId`).
mapping(bytes32 => CashInOperation) internal _cashIns;
```
2. Each time a cash-in operation is executed (through the `cashIn()` or `cashInBatch()` function call) it is checked whether an …
=> PIX. Tracking cash-in operations to prevent `txId` reusage

.openzeppelin/unknown-2008.json, contracts/PixCashier.sol, contracts/PixCashierStorage.sol, contracts/interfaces/IPixCashier.sol, docs/deployed-contracts.md, test/PixCashier.test.ts
closes cloudwalk/product-blockchain/issues/134
1.  The `batchId` parameter has been appended to the function for executing batch cash-in operations. The new function definition:
```solidity
function cashInBatch(
address[] memory accounts,
uint256[] memory amounts,
bytes32[] memory txIds,
bytes32 batchId
) external whenNotPaused onlyRole(CASHIER_ROLE) {}
```
2. Now, the `cashInBatch()` function along with the `CashIn` events for each cash-in operation in the batch emits a new `CashInBatch` event corresponding the batch operation as a whole. The definition of the new event:
```solidity
/**
* @dev Possible result statuses of a cash-in operation as an enum.
*
* The possible values:
* - Success --------- The operation was executed successfully.
* - AlreadyExecuted - The operation was already …
```
=> Improve cash-in batch operations 

contracts/CardPaymentProcessor.sol, contracts/CashbackDistributor.sol, contracts/PixCashier.sol, contracts/TokenDistributor.sol, contracts/base/AccessControlExtUpgradeable.sol, contracts/base/BlacklistableUpgradeable.sol, contracts/base/PausableExtUpgradeable.sol, contracts/base/RescuableUpgradeable.sol, contracts/mocks/base/AccessControlExtUpgradeableMock.sol, test/base/AccessControlExtUpgradeable.test.ts
**Main Changes**
This pull request overrides `AccessControlUpgradeable` with `AccessControlExtUpgradeable` to add batch functions:
- `grantRoleBatch` - grants role to batch of accounts
- `revokeRoleBatch` - revokes role from batch from accounts
**Test coverage**
File                                  |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------------------|----------|----------|----------|----------|----------------|
contracts/                           |      100 |    98.34 |      100 |      100 |                |
&nbsp;&nbsp;  CardPaymentProcessor.sol            |      100 |    99.28 |      100 |      100 |                |
&nbsp;&nbsp;  CardPaymentProcessorStorage.sol     |      100 |      100 |      100 |      100 |                | …
=> Override AccessControlUpgradeable contract

.env.example, .github/workflows/build.yml, .github/workflows/test.yml, README.md, contracts/CardPaymentProcessor.sol, contracts/interfaces/ICardPaymentProcessor.sol, hardhat.config.ts, package-lock.json, package.json, test/CardPaymentProcessor.test.ts
The payment merging functionality has been removed from the CPPv2 contract as not needed anymore.
The list of removed entities:
* event `PaymentExpanded`;
* event `PaymentMerged`;
* function `mergePayments()`;
* error `MergedPaymentCashbackRateMismatch`;
* error `MergedPaymentIdAndTargetPaymentIdEquality`;
* error `MergedPaymentIdArrayEmpty`;
* error `MergedPaymentPayerMismatch`;
* error `PaymentSubsidized`.
The `PaymentStatus.Merged` payment status has been kept for possible returning but marked in the comment as obsolete.
=> Remove payment merging functionality from CPPv2

contracts/CardPaymentProcessor.sol, contracts/CardPaymentProcessorStorage.sol, contracts/base/AccessControlExtUpgradeable.sol, contracts/base/BlocklistableUpgradeable.sol, contracts/base/PausableExtUpgradeable.sol, contracts/base/RescuableUpgradeable.sol, contracts/interfaces/ICardPaymentCashback.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/mocks/base/AccessControlExtUpgradeableMock.sol, contracts/mocks/base/BlocklistableUpgradeableMock.sol, contracts/mocks/base/PausableExtUpgradeableMock.sol, contracts/mocks/base/RescuableUpgradeableMock.sol, contracts/mocks/tokens/ERC20TokenMock.sol, test/CardPaymentProcessor.test.ts
1. The `Merged` payment status has been completely removed from the contract. The `PaymentStatus` enumeration values have been shifted. It might demand the appropriate changes of the backend.
2. It has been prohibited to make a payment with the zero sponsor address but non-zero subsidy limit. The transaction will be reverted with the `SponsorZeroAddress()` custom error in that case. Previously the subsidy limit would just be zeroed is the sponsor address was zero. The new check has been introduced to make the making payment logic more strict.
3. The new `TOKE_DECIMALS` public constant has been introduced to present the number of decimals that is used in the underlying token. 
4. Minor improvements in code and comments have been done.
=> Minor changes in CPPv2

package-lock.json, package.json, test-utils/eth.ts, test-utils/misc.ts, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts, test/base/AccessControlExtUpgradeable.test.ts, test/base/BlocklistableUpgradeable.test.ts, test/base/PausableExtUpgradeable.test.ts, test/base/RescuableUpgradeable.test.ts
1. The `@nomicfoundation/hardhat-toolbox` and `@openzeppelin/hardhat-upgrades` packages for contract testing and deployment have been updated to the latest versions that use the [EthersJS v.6](https://docs.ethers.org/v6/) library under the hood.
2. All the tests have been updated according to the new packages and the [EthersJS v.6](https://docs.ethers.org/v6/) library with minor refactoring.
3. The tests have added lines that now explicitly specify:
* the account used to deploy contracts under test;
* the initial (default) account that is used for interacting with the contracts under test.
4. The tests have been adopted to be run on the Stratus blockchain.
5. Additional helper functions have been introduced to simplify the tests.
No changes have been made.
=> Migrate tests to EthersJS v.6 with the Solidity compiler version updating

.openzeppelin/unknown-2008.json, .openzeppelin/unknown-2009.json
1. `CardPaymentProcessor` and `CashbackDistributor` contracts have been upgraded in Testnet.
2. `CardPaymentProcessor` and `CashbackDistributor` contracts upgrade have been prepared in Mainnet.
=> deploy: upgrade contracts in Testnet and Mainnet

contracts/CardPaymentProcessor.sol, contracts/interfaces/ICardPaymentProcessor.sol, test-utils/checkers.ts, test/CardPaymentProcessor.test.ts
1. The current base amount and extra amount of the canceled payment have been added to events `PaymentRevoked` and `PaymentReversed`.
2. The `data` parameter of payment-related events has been renamed to `addendum`. This is done to avoid confusion between the name of this parameter and the `data` part of blockchain transaction's logs.
3. The following entities have been separated in the contract code comments:
* `event parameters` -- the data that is included to blockchain events as their indexed or unindexed parameters;
* `addendum fields` --  the data that is included in dense-packing manner to the `addendum` parameter of payment-related events.
4. The current set of addendum fields for the `PaymentRevoked` and `PaymentReversed` events looks like:
```
- uint8(version) -- the version of …
```
=> feat: improve events of the CardPaymentProcessor V2 contract

.openzeppelin/unknown-2008.json, .openzeppelin/unknown-2009.json
- The `CardPaymentProcessor` contracts have been upgraded in Testnet and Mainnet (see changes [#67](https://github.com/cloudwalk/brlc-periphery/pull/67)).
- The `.openzeppelin` network files have been updated accordingly to smart contract upgrades.
=> Smart contracts upgrade in Testnet and Mainnet

.openzeppelin/unknown-2008.json, .openzeppelin/unknown-2009.json
- The `CardPaymentProcessor` contracts have been upgraded in Testnet and Mainnet (see changes [#70](https://github.com/cloudwalk/brlc-periphery/pull/70)).
- The `.openzeppelin` network files have been updated accordingly to smart contract upgrades.
=> The CPPv1 smart-contract upgrade in Testnet and Mainnet

.openzeppelin/unknown-2008.json, .openzeppelin/unknown-2009.json
- The `CardPaymentProcessor` contracts have been upgraded in Testnet and Mainnet (see changes [#69](https://github.com/cloudwalk/brlc-periphery/pull/69)).
- The `.openzeppelin` network files have been updated accordingly to smart contract upgrades.
=> The CPPv2 smart-contract upgrade in Testnet and Mainnet

test/CashbackDistributor.test.ts
An incorrect time shift caused tests on the Stratus network to fail. This has now been fixed.
=> test: fix block time shift value

contracts/CardPaymentProcessor.sol, contracts/base/UUPSExtUpgradeable.sol, contracts/base/Versionable.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/mocks/base/UUPSExtUpgradableMock.sol, test/CardPaymentProcessor.test.ts, test/base/UUPSExtUbgradable.test.ts
1. The new `UUPSExtUpgradeable` contract has been introduced for internal usage through inheritance.
2. The new contract provides additional checks during the upgrade, making the procedure safer.
3. A new marker function named `proveCardPaymentProcessor()` has been added to the `CardPaymentProcessor` contract for use in conjunction with the new `UUPSExtUpgradeable` contract. When upgrading, that function ensures that the new implementation of the contract is compatible.
The version of the `CardPaymentProcessor` contract has been changed: `2.0.0` => `2.1.0`.
New functionality was fully covered by tests.
=> feat: introduce `UUPSExtUpgradeable` base contract

contracts/CashbackDistributor.sol, contracts/CashbackDistributorStorage.sol, contracts/base/Versionable.sol, contracts/interfaces/ICashbackDistributor.sol, contracts/mocks/CashbackDistributorMock.sol, package-lock.json, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts
1. The new function `previewCashbackCap()` has been added to the `CashbackDistributor` smart contract. The new function determines the sate of the periodical cashback cap at the current block timestamp (at the call moment):
<details>
<summary>The definition of the new function </summary>
```solidity
/**
* @dev Determines a preview of the cashback cap state for a token and a recipient at the current block timestamp.
* @param token The token contract address of the cashback operations to define the returned cashback cap state.
* @param recipient The recipient address of the cashback operations to define the returned cashback cap state.
* @return cashbackPeriodStart The start time of the current cashback cap period.
* @return overallCashbackForPeriod The total amount of cashback within the …
```
=> feat: add the cashback cap preview function to CashbackDistributor

.gitignore, .mocharc.json, contracts/CardPaymentProcessor.sol, contracts/CashbackDistributor.sol, contracts/base/Versionable.sol, contracts/interfaces/ICardPaymentProcessor.sol, contracts/interfaces/ICashbackDistributor.sol, contracts/mocks/CashbackDistributorMock.sol, contracts/mocks/tokens/ERC20TokenMock.sol, test/CardPaymentProcessor.test.ts, test/CashbackDistributor.test.ts
Closes https://github.com/cloudwalk/product-smart-contracts/issues/211
1. Changed token flow related to cashback. Now the `CashbackDistributor`(CD) smart contract sends cashback directly to user and claws it from user if needed.
2. When cashback is revoked CD claws tokens directly from cashback recipient, instead of `msg.sender`.
2. The `CardPaymentProcessor` (CPP) smart contract and the cash-out account (COA) now sends full payment refund to user, without applying cashback to refund amount.
3. The calculation logic for the `sentAmount` parameter of the following CPP events has been changed: `RevokePayment`, `ReversePayment`, `RefundPayment`. See details in the appropriate section below.
4. Fixed and corrected all tests to support new token flow.
No changes.
1. Account → (payment amount) …
=> feat: new token flow on cashback revocation
